dfs.namenode.max.op.size	52428800	ERROR	Task: attempt_1701312551309_0578_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null		30