name,value,relevant log,explanation
io.bytes.per.checksum,960512577,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).
	",value-hit
ha.health-monitor.rpc.connect.max.retries,1,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).
	",value-hit
yarn.nodemanager.localizer.client.thread-count,5,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).
	",value-hit
io.bytes.per.checksum,960512577,ERROR	Task: attempt_1701312551309_0640_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
yarn.app.attempt.diagnostics.limit.kc,64,ERROR	Task: attempt_1701312551309_0640_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
ha.health-monitor.rpc.connect.max.retries,1,ERROR	Task: attempt_1701312551309_0640_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
yarn.nodemanager.localizer.client.thread-count,5,ERROR	Task: attempt_1701312551309_0640_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
fs.s3a.threads.max,64,ERROR	Task: attempt_1701312551309_0640_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
io.bytes.per.checksum,960512577,INFO	Diagnostics report from attempt_1701312551309_0640_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
yarn.app.attempt.diagnostics.limit.kc,64,INFO	Diagnostics report from attempt_1701312551309_0640_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
ha.health-monitor.rpc.connect.max.retries,1,INFO	Diagnostics report from attempt_1701312551309_0640_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
yarn.nodemanager.localizer.client.thread-count,5,INFO	Diagnostics report from attempt_1701312551309_0640_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
fs.s3a.threads.max,64,INFO	Diagnostics report from attempt_1701312551309_0640_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=960512577) must divide block size (=134217728).	,value-hit
ha.health-monitor.rpc.connect.max.retries,1,INFO	1 failures on node ed761ad59d44,value-hit
yarn.nodemanager.localizer.client.thread-count,5,INFO	1 failures on node ed761ad59d44,value-hit
io.bytes.per.checksum,960512577,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
ha.health-monitor.rpc.connect.max.retries,1,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,960512577,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
ha.health-monitor.rpc.connect.max.retries,1,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,960512577,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,960512577,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
ha.health-monitor.rpc.connect.max.retries,1,INFO	Exiting with status 1: java.lang.NullPointerException,value-hit
