name:io.bytes.per.checksum
value:0
relevant log:1-ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
explanation:The configuration option 'io.bytes.per.checksum' is set to 0, which is causing an Invalid checksum type error. This option determines the number of bytes per checksum and should not be set to 0.

name:yarn.nodemanager.runtime.linux.runc.layer-mounts-to-keep
value:<missing>
relevant log:2-INFO	Diagnostics report from attempt_1701457076904_0039_m_000004_0: [2023-12-02 04:01:54.326]Exception when trying to cleanup container container_1701457076904_0039_01_000008: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701457076904_0039/container_1701457076904_0039_01_000008/container_1701457076904_0039_01_000008.pid (No such file or directory)
explanation:The configuration option 'yarn.nodemanager.runtime.linux.runc.layer-mounts-to-keep' is missing a value. This could be causing the FileNotFoundException error as the system may not know how many layer mounts to keep.

name:dfs.namenode.get-blocks.max-qps
value:20
relevant log:3-ERROR	Task: attempt_1701457076904_0039_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
explanation:The configuration option 'dfs.namenode.get-blocks.max-qps' is set to 20, which may be too low and causing the Invalid checksum type error. This option determines the maximum number of getBlocks RPCs data movement utilities can make to a NameNode per second.