name,value,relevant log,explanation
io.bytes.per.checksum,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
dfs.checksum.ec.socket-timeout,3000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	checksum
dfs.checksum.ec.socket-timeout,3000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	ec
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	check
io.bytes.per.checksum,0,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
hadoop.security.kms.client.authentication.retry-count,1,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.checksum.ec.socket-timeout,3000,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	checksum
dfs.checksum.ec.socket-timeout,3000,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	ec
yarn.app.attempt.diagnostics.limit.kc,64,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	attempt
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"ERROR	Task: attempt_1701312551309_0345_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	check
io.bytes.per.checksum,0,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
hadoop.security.kms.client.authentication.retry-count,1,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.checksum.ec.socket-timeout,3000,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	checksum
dfs.checksum.ec.socket-timeout,3000,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	ec
yarn.app.attempt.diagnostics.limit.kc,64,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	attempt
yarn.app.attempt.diagnostics.limit.kc,64,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	diagnostics
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"INFO	Diagnostics report from attempt_1701312551309_0345_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	check
hadoop.security.kms.client.authentication.retry-count,1,INFO	1 failures on node cf6e5ca2712c,value-hit
io.bytes.per.checksum,0,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,0,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
hadoop.security.kms.client.authentication.retry-count,1,INFO	Exiting with status 1: java.lang.NullPointerException,value-hit
