name,value,relevant log,explanation
io.bytes.per.checksum,-1617708091,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null
	",value-hit
mapreduce.job.ubertask.maxmaps,9,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null
	",value-hit
fs.trash.checkpoint.interval,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null
	",value-hit
dfs.ha.fencing.ssh.connect-timeout,30000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null
	",property-item-hit	ha
hadoop.security.group.mapping.ldap.num.attempts,3,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null
	",value-hit
io.bytes.per.checksum,-1617708091,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
mapreduce.job.ubertask.maxmaps,9,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
fs.trash.checkpoint.interval,0,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
dfs.ha.fencing.ssh.connect-timeout,30000,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",property-item-hit	ha
hadoop.security.group.mapping.ldap.num.attempts,3,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
hadoop.security.groups.negative-cache.secs,30,"ERROR	Task: attempt_1701312551309_0463_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
io.bytes.per.checksum,-1617708091,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
mapreduce.job.ubertask.maxmaps,9,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
fs.trash.checkpoint.interval,0,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
dfs.ha.fencing.ssh.connect-timeout,30000,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",property-item-hit	ha
hadoop.security.group.mapping.ldap.num.attempts,3,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
hadoop.security.groups.negative-cache.secs,30,"INFO	Diagnostics report from attempt_1701312551309_0463_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1617708091, effective=null	",value-hit
io.bytes.per.checksum,-1617708091,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
dfs.ha.fencing.ssh.connect-timeout,30000,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,-1617708091,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
dfs.ha.fencing.ssh.connect-timeout,30000,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	ha
io.bytes.per.checksum,-1617708091,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,-1617708091,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
