name,value,relevant log,explanation
io.bytes.per.checksum,1720753167,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1693090681
	",property-item-hit	io
dfs.qjournal.http.read.timeout.ms,60000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1693090681
	",property-item-hit	read
hadoop.security.groups.cache.background.reload.threads,3,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.java.lang.NegativeArraySizeException: -1693090681
	",value-hit
io.bytes.per.checksum,1720753167,ERROR	Task: attempt_1701312551309_0468_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1693090681	,property-item-hit	io
hadoop.security.groups.cache.background.reload.threads,3,ERROR	Task: attempt_1701312551309_0468_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1693090681	,value-hit
fs.s3a.retry.limit,7,ERROR	Task: attempt_1701312551309_0468_r_000000_0 - exited : java.lang.NegativeArraySizeException: -1693090681	,value-hit
io.bytes.per.checksum,1720753167,INFO	Diagnostics report from attempt_1701312551309_0468_r_000000_0: Error: java.lang.NegativeArraySizeException: -1693090681	,property-item-hit	io
hadoop.security.groups.cache.background.reload.threads,3,INFO	Diagnostics report from attempt_1701312551309_0468_r_000000_0: Error: java.lang.NegativeArraySizeException: -1693090681	,value-hit
fs.s3a.retry.limit,7,INFO	Diagnostics report from attempt_1701312551309_0468_r_000000_0: Error: java.lang.NegativeArraySizeException: -1693090681	,value-hit
fs.s3a.retry.limit,7,INFO	1 failures on node ed761ad59d44,value-hit
io.bytes.per.checksum,1720753167,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,1720753167,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,1720753167,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,1720753167,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
