name,value,relevant log,explanation
io.bytes.per.checksum,-2040322260,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
dfs.datanode.block.id.layout.upgrade.threads,6,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
yarn.client.failover-retries,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
dfs.namenode.max.full.block.report.leases,6,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
hadoop.security.group.mapping.ldap.num.attempts,3,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
dfs.namenode.max.objects,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null
	",value-hit
io.bytes.per.checksum,-2040322260,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.datanode.block.id.layout.upgrade.threads,6,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
yarn.client.failover-retries,0,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.namenode.max.full.block.report.leases,6,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
hadoop.security.group.mapping.ldap.num.attempts,3,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.namenode.max.objects,0,"ERROR	Task: attempt_1701359859177_0078_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
io.bytes.per.checksum,-2040322260,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.datanode.block.id.layout.upgrade.threads,6,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
yarn.client.failover-retries,0,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.namenode.max.full.block.report.leases,6,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
hadoop.security.group.mapping.ldap.num.attempts,3,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.namenode.max.objects,0,"INFO	Diagnostics report from attempt_1701359859177_0078_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-2040322260, effective=null	",value-hit
dfs.datanode.block.id.layout.upgrade.threads,6,INFO	1 failures on node ed761ad59d44,value-hit
dfs.namenode.max.full.block.report.leases,6,INFO	1 failures on node ed761ad59d44,value-hit
io.bytes.per.checksum,-2040322260,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.top.window.num.buckets,10,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	top
io.bytes.per.checksum,-2040322260,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.top.window.num.buckets,10,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	top
io.bytes.per.checksum,-2040322260,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.top.window.num.buckets,10,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	top
io.bytes.per.checksum,-2040322260,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
