name,value,relevant log,explanation
io.bytes.per.checksum,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
dfs.namenode.max.op.size,52428800,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	op
hadoop.security.kms.client.encrypted.key.cache.num.refill.threads,2,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
io.bytes.per.checksum,0,"ERROR	Task: attempt_1701312551309_0255_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
mapreduce.task.merge.progress.records,10000,"ERROR	Task: attempt_1701312551309_0255_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	task
dfs.namenode.max.op.size,52428800,"ERROR	Task: attempt_1701312551309_0255_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	op
hadoop.security.kms.client.encrypted.key.cache.num.refill.threads,2,"ERROR	Task: attempt_1701312551309_0255_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
fs.s3a.retry.limit,7,"ERROR	Task: attempt_1701312551309_0255_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
io.bytes.per.checksum,0,"INFO	Diagnostics report from attempt_1701312551309_0255_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.namenode.max.op.size,52428800,"INFO	Diagnostics report from attempt_1701312551309_0255_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	op
hadoop.security.kms.client.encrypted.key.cache.num.refill.threads,2,"INFO	Diagnostics report from attempt_1701312551309_0255_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
fs.s3a.retry.limit,7,"INFO	Diagnostics report from attempt_1701312551309_0255_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
hadoop.security.kms.client.encrypted.key.cache.num.refill.threads,2,INFO	1 failures on node cf6e5ca2712c,value-hit
fs.s3a.retry.limit,7,INFO	1 failures on node cf6e5ca2712c,value-hit
io.bytes.per.checksum,0,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.max.op.size,52428800,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	op
io.bytes.per.checksum,0,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.max.op.size,52428800,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	op
io.bytes.per.checksum,0,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
dfs.namenode.max.op.size,52428800,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	op
io.bytes.per.checksum,0,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
