name,value,relevant log,explanation
io.bytes.per.checksum,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
dfs.namenode.file.close.num-committed-allowed,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
fs.s3a.list.version,2,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",value-hit
dfs.ha.tail-edits.rolledits.timeout,60,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	ha
io.mapfile.bloom.size,1048576,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null
	",property-item-hit	io
io.bytes.per.checksum,0,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.client.datanode-restart.timeout,30,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.namenode.file.close.num-committed-allowed,0,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
fs.s3a.list.version,2,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.ha.tail-edits.rolledits.timeout,60,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	ha
io.mapfile.bloom.size,1048576,"ERROR	Task: attempt_1701312551309_0597_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	io
io.bytes.per.checksum,0,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.client.datanode-restart.timeout,30,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.namenode.file.close.num-committed-allowed,0,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
fs.s3a.list.version,2,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",value-hit
dfs.ha.tail-edits.rolledits.timeout,60,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	ha
io.mapfile.bloom.size,1048576,"INFO	Diagnostics report from attempt_1701312551309_0597_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:0, effective=null	",property-item-hit	io
fs.s3a.list.version,2,INFO	1 failures on node cf6e5ca2712c,value-hit
io.bytes.per.checksum,0,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
dfs.ha.tail-edits.rolledits.timeout,60,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	ha
io.mapfile.bloom.size,1048576,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
yarn.nodemanager.runtime.linux.docker.stop.grace-period,10,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	stop
io.bytes.per.checksum,0,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
dfs.ha.tail-edits.rolledits.timeout,60,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	ha
io.mapfile.bloom.size,1048576,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
yarn.nodemanager.runtime.linux.docker.stop.grace-period,10,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	stop
io.bytes.per.checksum,0,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.mapfile.bloom.size,1048576,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
yarn.nodemanager.runtime.linux.docker.stop.grace-period,10,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	stop
io.bytes.per.checksum,0,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
io.mapfile.bloom.size,1048576,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
