dfs.client.test.drop.namenode.response.number	0	ERROR	Task: attempt_1701457076904_0550_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1773637460, effective=null		30