name,value,relevant log,explanation
io.bytes.per.checksum,-1269538164,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",value-hit
yarn.app.attempt.diagnostics.limit.kc,64,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",value-hit
dfs.client.read.shortcircuit.streams.cache.expiry.ms,300000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",property-item-hit	read
dfs.client.socketcache.capacity,16,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",value-hit
ha.failover-controller.graceful-fence.connection.retries,1,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",value-hit
ipc.client.connect.max.retries.on.timeouts,45,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null
	",property-item-hit	on
io.bytes.per.checksum,-1269538164,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
yarn.app.attempt.diagnostics.limit.kc,64,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
dfs.client.socketcache.capacity,16,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
ha.failover-controller.graceful-fence.connection.retries,1,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
dfs.image.transfer-bootstrap-standby.bandwidthPerSec,0,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
ipc.client.connect.max.retries.on.timeouts,45,"ERROR	Task: attempt_1701312551309_0659_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",property-item-hit	on
io.bytes.per.checksum,-1269538164,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
yarn.app.attempt.diagnostics.limit.kc,64,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
dfs.client.socketcache.capacity,16,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
ha.failover-controller.graceful-fence.connection.retries,1,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
dfs.image.transfer-bootstrap-standby.bandwidthPerSec,0,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",value-hit
ipc.client.connect.max.retries.on.timeouts,45,"INFO	Diagnostics report from attempt_1701312551309_0659_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1269538164, effective=null	",property-item-hit	on
ha.failover-controller.graceful-fence.connection.retries,1,INFO	1 failures on node cf6e5ca2712c,value-hit
ipc.client.connect.max.retries.on.timeouts,45,INFO	1 failures on node cf6e5ca2712c,property-item-hit	on
io.bytes.per.checksum,-1269538164,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
ha.failover-controller.graceful-fence.connection.retries,1,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	ha
ipc.client.connect.max.retries.on.timeouts,45,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	on
io.bytes.per.checksum,-1269538164,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
ha.failover-controller.graceful-fence.connection.retries,1,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	ha
ipc.client.connect.max.retries.on.timeouts,45,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	on
io.bytes.per.checksum,-1269538164,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
ipc.client.connect.max.retries.on.timeouts,45,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	on
io.bytes.per.checksum,-1269538164,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
ha.failover-controller.graceful-fence.connection.retries,1,INFO	Exiting with status 1: java.lang.NullPointerException,value-hit
ipc.client.connect.max.retries.on.timeouts,45,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	on
