name,value,relevant log,explanation
io.bytes.per.checksum,-1007046151,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null
	",value-hit
dfs.namenode.blockreport.max.lock.hold.time,4,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null
	",value-hit
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null
	",property-item-hit	check
dfs.client.test.drop.namenode.response.number,0,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null
	",value-hit
dfs.namenode.blockreport.max.lock.hold.time,4,INFO	DefaultSpeculator.addSpeculativeAttempt -- we are speculating task_1701457076904_0376_m_000008,value-hit
dfs.client.test.drop.namenode.response.number,0,INFO	DefaultSpeculator.addSpeculativeAttempt -- we are speculating task_1701457076904_0376_m_000008,value-hit
io.bytes.per.checksum,-1007046151,"ERROR	Task: attempt_1701457076904_0376_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
dfs.namenode.blockreport.max.lock.hold.time,4,"ERROR	Task: attempt_1701457076904_0376_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"ERROR	Task: attempt_1701457076904_0376_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",property-item-hit	check
dfs.client.test.drop.namenode.response.number,0,"ERROR	Task: attempt_1701457076904_0376_r_000000_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
io.bytes.per.checksum,-1007046151,"INFO	Diagnostics report from attempt_1701457076904_0376_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
dfs.namenode.blockreport.max.lock.hold.time,4,"INFO	Diagnostics report from attempt_1701457076904_0376_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
dfs.short.circuit.shared.memory.watcher.interrupt.check.ms,60000,"INFO	Diagnostics report from attempt_1701457076904_0376_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",property-item-hit	check
dfs.client.test.drop.namenode.response.number,0,"INFO	Diagnostics report from attempt_1701457076904_0376_r_000000_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid checksum type: userOpt=null, default=CRC32C:-1007046151, effective=null	",value-hit
dfs.namenode.blockreport.max.lock.hold.time,4,INFO	1 failures on node ed761ad59d44,value-hit
io.bytes.per.checksum,-1007046151,"INFO	Service JobHistoryEventHandler failed in state STOPPEDjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,-1007046151,"WARN	When stopping the service JobHistoryEventHandlerjava.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,-1007046151,"WARN	Graceful stop failed. Exiting..java.lang.NullPointerException
	",property-item-hit	io
io.bytes.per.checksum,-1007046151,INFO	Exiting with status 1: java.lang.NullPointerException,property-item-hit	io
